### ISSUE TITLE
Update the link to the organization's website

### ISSUE THREAD

**Issue by okineadev** [vitejs/.github#7]
Update the org link to https://vite.dev

![image](https://github.com/user-attachments/assets/78c2c239-1e4b-484e-983d-019f1fd86b7d)

**Comment by patak-dev** [comment]
Thanks for the heads up. Also added our other social accounts
<img width="773" alt="image" src="https://github.com/user-attachments/assets/08859646-73e6-4814-b020-af78ef60cf01">
